import js from '@eslint/js'
import globals from 'globals'
import reactHooks from 'eslint-plugin-react-hooks'
import reactRefresh from 'eslint-plugin-react-refresh'
import jsxA11y from 'eslint-plugin-jsx-a11y'
import importX from 'eslint-plugin-import-x'
import tseslint from 'typescript-eslint'
import prettierConfig from 'eslint-config-prettier'
import { defineConfig, globalIgnores } from 'eslint/config'

export default defineConfig([
  // `src/client` is generated by @hey-api/openapi-ts (npm run gen:types) and is
  // never hand-edited — it intentionally violates lint rules (unused params,
  // assertions), so ignore the whole tree.
  globalIgnores(['dist', 'src/client']),
  {
    files: ['**/*.{ts,tsx}'],
    extends: [
      js.configs.recommended,
      tseslint.configs.recommended,
      reactHooks.configs.flat.recommended,
      reactRefresh.configs.vite,
      // Accessibility linting for JSX. Landed as warnings (see rules below) so
      // the existing backlog — notably the keyboard-inaccessible Kanban board /
      // modals (ProjectBoard.tsx) — stays visible without turning CI red.
      jsxA11y.flatConfigs.recommended,
      // Must come last: disables any ESLint stylistic rules that would
      // conflict with Prettier's formatting.
      prettierConfig,
    ],
    plugins: {
      'import-x': importX,
    },
    languageOptions: {
      ecmaVersion: 2020,
      globals: globals.browser,
    },
    rules: {
      // Land every jsx-a11y recommended rule as a warning rather than an error.
      // The codebase has a known a11y backlog (keyboard-inaccessible Kanban
      // board + modals — see app/CLAUDE.md); we want it visible, not blocking
      // CI, and remediated in a dedicated follow-up. Computed so new rules added
      // to the recommended set in future plugin versions stay warn automatically.
      ...Object.fromEntries(
        Object.keys(jsxA11y.flatConfigs.recommended.rules).map((rule) => [rule, 'warn']),
      ),
      // Import ordering: builtin → external → internal (@/* alias) → relative,
      // alphabetized. `error` because it is fully autofixable via `eslint --fix`.
      // `newlines-between` is intentionally left unset: enforcing it conflicts
      // unfixably with side-effect CSS imports (e.g. `import './App.css'`).
      'import-x/order': [
        'error',
        {
          groups: ['builtin', 'external', 'internal', ['parent', 'sibling', 'index']],
          pathGroups: [{ pattern: '@/**', group: 'internal', position: 'before' }],
          pathGroupsExcludedImportTypes: ['builtin'],
          alphabetize: { order: 'asc', caseInsensitive: true },
        },
      ],
      // `any` is banned. The legacy backlog (API response shapes, recharts
      // payloads, drag/calendar event types) was burned down and replaced with
      // real types / `unknown` + narrowing, so this is an error to keep it gone.
      '@typescript-eslint/no-explicit-any': 'error',
      // Keep stray debug logging out of production code; console.warn/error are
      // allowed for genuine diagnostics.
      'no-console': ['warn', { allow: ['warn', 'error'] }],
      // Allow `_`-prefixed identifiers and ignore unused catch params entirely
      // (we frequently write `} catch { ... }` or `} catch (_err) { ... }`).
      '@typescript-eslint/no-unused-vars': [
        'error',
        {
          argsIgnorePattern: '^_',
          varsIgnorePattern: '^_',
          caughtErrors: 'none',
        },
      ],
      // Style Guide 1a: keep the neutral/info/progress colors coming from tokens,
      // not raw hexes. These have exact utility/CSS-var equivalents and no
      // legitimate literal use (unlike brand-gold gradients and chart series,
      // which are intentionally left literal and NOT matched here). Warn-level so
      // it's loud, not blocking — matching the repo's lint posture.
      // Scoped to className strings — the actual anti-pattern. Data literals
      // (palettes, chart series, config color maps) legitimately hold hexes and
      // are intentionally NOT matched.
      'no-restricted-syntax': [
        'warn',
        {
          selector:
            "JSXAttribute[name.name='className'] Literal[value=/#(?:[Aa]6[Aa]29[Cc]|5[Bb]9[Bb][Ee]6|8[Aa]8[Aa]8[Aa]|[Ff]5[Ff]3[Ee][Ff]|6[Ee]6[Aa]64)/]",
          message:
            'Use a color token instead of a raw hex in className: text-muted-foreground (#A6A29C), text-info (#5B9BE6), bg-progress (#8A8A8A), text-foreground (#F5F3EF), text-ink-low (#6E6A64).',
        },
        {
          // Same rule for hexes baked into template-literal classNames
          // (className={`… #A6A29C …`}) — the Literal selector above can't see
          // TemplateElement quasis.
          selector:
            "JSXAttribute[name.name='className'] TemplateElement[value.raw=/#(?:[Aa]6[Aa]29[Cc]|5[Bb]9[Bb][Ee]6|8[Aa]8[Aa]8[Aa]|[Ff]5[Ff]3[Ee][Ff]|6[Ee]6[Aa]64)/]",
          message:
            'Use a color token instead of a raw hex in className: text-muted-foreground (#A6A29C), text-info (#5B9BE6), bg-progress (#8A8A8A), text-foreground (#F5F3EF), text-ink-low (#6E6A64).',
        },
      ],
    },
  },
  {
    // shadcn-generated UI primitives intentionally co-export utility hooks,
    // variants, and constants alongside the component. The react-refresh
    // restriction doesn't apply because we don't HMR these files in practice.
    files: [
      'src/components/ui/**/*.{ts,tsx}',
      'src/contexts/**/*.{ts,tsx}',
    ],
    rules: {
      'react-refresh/only-export-components': 'off',
    },
  },
  {
    // Test files deliberately interleave `vi.mock(...)` calls between import
    // statements (vitest hoisted-mock pattern): the mock must be declared
    // before the imports whose modules it intercepts. That ordering is
    // semantic, not stylistic, so import-x/order can't safely sort it — turn
    // it off here rather than fight the convention.
    files: ['**/*.test.{ts,tsx}', 'src/test/**/*.{ts,tsx}'],
    rules: {
      'import-x/order': 'off',
    },
  },
])
